# Generated by Django 3.2.7 on 2021-09-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='description',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='apps',
            name='image',
            field=models.ImageField(default='', height_field=600, upload_to='', width_field=800),
        ),
        migrations.AddField(
            model_name='apps',
            name='url',
            field=models.URLField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='apps',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
