# Generated by Django 3.2.7 on 2021-09-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_apps_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='image',
            field=models.ImageField(default='', height_field='600', upload_to='.', width_field='800'),
        ),
    ]
