# Generated by Django 3.2.7 on 2021-09-20 07:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_auto_20210920_0743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apps',
            old_name='publish_time',
            new_name='last_update',
        ),
        migrations.AddField(
            model_name='apps',
            name='published_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
