# Generated by Django 3.2.7 on 2021-09-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_auto_20210920_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='platforms',
            field=models.CharField(choices=[('PWA', 'Progressive Web App'), ('IOS', 'native IOS'), ('Android', 'native android'), ('Flutter', 'Cross platform by Flutter'), ('Desktop Win', 'native windows'), ('Desktop mac', 'native macintosh'), ('Desktop Linux', 'native linux')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
