# Generated by Django 3.2.7 on 2021-09-20 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_apps_platforms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apps',
            name='platforms',
        ),
    ]
