# Generated by Django 3.2.7 on 2021-09-20 08:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_remove_apps_platforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('PWA', 'Progressive Web App'), ('IOS', 'native IOS'), ('Android', 'native android'), ('Flutter', 'Cross platform by Flutter'), ('Desktop Win', 'native windows'), ('Desktop mac', 'native macintosh'), ('Desktop Linux', 'native linux')], default='', max_length=61),
            preserve_default=False,
        ),
    ]
