# Generated by Django 3.2.7 on 2021-09-20 08:14

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_apps_platforms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apps',
            old_name='url',
            new_name='android_url',
        ),
        migrations.AddField(
            model_name='apps',
            name='desk_lin_url',
            field=models.URLField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='apps',
            name='desk_mac_url',
            field=models.URLField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='apps',
            name='desk_win_url',
            field=models.URLField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='apps',
            name='ios_url',
            field=models.URLField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='apps',
            name='web_url',
            field=models.URLField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='apps',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('PWA', 'Progressive Web App'), ('IOS', 'Native IOS'), ('Android', 'Native android'), ('Flutter', 'Cross platform by Flutter'), ('Desktop Win', 'Native windows'), ('Desktop mac', 'Native macintosh'), ('Desktop Linux', 'Native linux')], max_length=61),
        ),
    ]
