# Generated by Django 3.2.7 on 2021-09-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
