# Generated by Django 3.2.7 on 2021-09-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='vote_down',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_up',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
