# Generated by Django 3.2.7 on 2021-09-24 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='vote_down',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_up',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('content', models.TextField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='apps.apps')),
            ],
        ),
    ]
