# Generated by Django 3.2.7 on 2021-09-24 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_alter_vote_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='comment',
            new_name='suggestion',
        ),
    ]
