# Generated by Django 3.2.7 on 2021-09-25 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0022_rename_comment_vote_suggestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='suggestion',
            options={'ordering': ('created_at',)},
        ),
    ]
