# Generated by Django 3.2.7 on 2021-09-26 10:40

import apps.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0024_auto_20210925_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=apps.models.image_upload, validators=[django.core.validators.FileExtensionValidator(['png', 'svg'])]),
        ),
    ]
