# Generated by Django 3.2.7 on 2021-09-26 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0025_alter_apps_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['png', 'svg', 'jpg', 'jpeg'])]),
        ),
    ]
