# Generated by Django 3.2.7 on 2021-09-27 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0026_alter_apps_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='.', validators=[django.core.validators.FileExtensionValidator(['png'])]),
        ),
    ]
