# Generated by Django 3.2.7 on 2021-09-27 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0027_alter_apps_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_down',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_up',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1)]),
        ),
    ]
