# Generated by Django 3.2.7 on 2022-04-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0028_auto_20210927_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
